Python 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.

= RESTART: C:/Users/Roden Marc/OneDrive/Desktop/DSA 2ND SEM PROJECTS SHIKII/ZeroNegPosNumberChecker.py
INPUT INTEGER VALUE: 5
THE NUMBER 5.0  IS POSITIVE
INPUT INTEGER VALUE: 8
THE NUMBER 8.0  IS POSITIVE
INPUT INTEGER VALUE: -8
THE NUMBER -8.0  IS POSITIVE
INPUT INTEGER VALUE: 
= RESTART: C:/Users/Roden Marc/OneDrive/Desktop/DSA 2ND SEM PROJECTS SHIKII/ZeroNegPosNumberChecker.py
INPUT INTEGER VALUE: 5
INPUT INTEGER VALUE: 
= RESTART: C:/Users/Roden Marc/OneDrive/Desktop/DSA 2ND SEM PROJECTS SHIKII/ZeroNegPosNumberChecker.py
INPUT INTEGER VALUE: 5
INPUT INTEGER VALUE: 6
INPUT INTEGER VALUE: 
= RESTART: C:/Users/Roden Marc/OneDrive/Desktop/DSA 2ND SEM PROJECTS SHIKII/ZeroNegPosNumberChecker.py
INPUT INTEGER VALUE: 5
INPUT INTEGER VALUE: 6
INPUT INTEGER VALUE: 5
INPUT INTEGER VALUE: 
= RESTART: C:/Users/Roden Marc/OneDrive/Desktop/DSA 2ND SEM PROJECTS SHIKII/ZeroNegPosNumberChecker.py
INPUT INTEGER VALUE: 6
THE NUMBER 6  IS POSITIVE
INPUT INTEGER VALUE: -8
THE NUMBER -8  IS NEGATIVE
INPUT INTEGER VALUE: 0
THE NUMBER 0 IS ZERO
INPUT INTEGER VALUE: 0
THE NUMBER 0 IS ZERO
INPUT INTEGER VALUE: 0
THE NUMBER 0 IS ZERO
INPUT INTEGER VALUE: 0
THE NUMBER 0 IS ZERO
INPUT INTEGER VALUE: 999
THE NUMBER 999  IS POSITIVE
INPUT INTEGER VALUE: a
Traceback (most recent call last):
  File "C:/Users/Roden Marc/OneDrive/Desktop/DSA 2ND SEM PROJECTS SHIKII/ZeroNegPosNumberChecker.py", line 5, in <module>
    num1 = int(input("INPUT INTEGER VALUE: "))
ValueError: invalid literal for int() with base 10: 'a'

=== RESTART: C:/Users/Roden Marc/OneDrive/Desktop/DSA 2ND SEM PROJECTS SHIKII/ZeroNegPosNumberChecker.py ==
INPUT INTEGER VALUE: 8
THE NUMBER 8  IS POSITIVE
INPUT INTEGER VALUE: 2
THE NUMBER 2  IS POSITIVE
INPUT INTEGER VALUE: 0
THE NUMBER 0 IS ZERO
INPUT INTEGER VALUE: 3
THE NUMBER 3  IS POSITIVE
INPUT INTEGER VALUE: 0
THE NUMBER 0 IS ZERO
INPUT INTEGER VALUE: 0
THE NUMBER 0 IS ZERO
INPUT INTEGER VALUE: -9
THE NUMBER -9  IS NEGATIVE
INPUT INTEGER VALUE: A
THE INPUT INTEGER IS INVALID
A
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    A
NameError: name 'A' is not defined

=== RESTART: C:/Users/Roden Marc/OneDrive/Desktop/DSA 2ND SEM PROJECTS SHIKII/ZeroNegPosNumberChecker.py ==
INPUT INTEGER VALUE: A
THE INPUT INTEGER IS INVALID
INPUT INTEGER VALUE: A
THE INPUT INTEGER IS INVALID
INPUT INTEGER VALUE: A
THE INPUT INTEGER IS INVALID
INPUT INTEGER VALUE: !@!@
THE INPUT INTEGER IS INVALID
INPUT INTEGER VALUE: 05
THE NUMBER 5  IS POSITIVE
INPUT INTEGER VALUE: 9
THE NUMBER 9  IS POSITIVE
INPUT INTEGER VALUE: 
=== RESTART: C:/Users/Roden Marc/OneDrive/Desktop/DSA 2ND SEM PROJECTS SHIKII/ZeroNegPosNumberChecker.py ==
INPUT INTEGER VALUE: 0555
THE NUMBER 555  IS POSITIVE
INPUT INTEGER VALUE: -999
THE NUMBER -999  IS NEGATIVE
INPUT INTEGER VALUE: 0
THE NUMBER 0 IS ZERO
INPUT INTEGER VALUE: 0
THE NUMBER 0 IS ZERO
INPUT INTEGER VALUE: 0
THE NUMBER 0 IS ZERO
INPUT INTEGER VALUE: 1995
THE NUMBER 1995  IS POSITIVE
INPUT INTEGER VALUE: HAHAAHAHA
THE INPUT INTEGER IS INVALID
INPUT INTEGER VALUE: 
= RESTART: C:/Users/Roden Marc/OneDrive/Desktop/DSA 2ND SEM PROJECTS SHIKII/GuessTheLuckyNumberChecker.py =
INPUT YOUR GUESS LUCKY NUMBER: 1
TRY AGAIN! 1.0 IS NOT A LUCKY NUMBERS
INPUT YOUR GUESS LUCKY NUMBER: 
= RESTART: C:/Users/Roden Marc/OneDrive/Desktop/DSA 2ND SEM PROJECTS SHIKII/GuessTheLuckyNumberChecker.py =
INPUT YOUR GUESS LUCKY NUMBER: 5
TRY AGAIN! 5 IS NOT A LUCKY NUMBERS
INPUT YOUR GUESS LUCKY NUMBER: 3
TRY AGAIN! 3 IS NOT A LUCKY NUMBERS
INPUT YOUR GUESS LUCKY NUMBER: 0
TRY AGAIN! 0 IS NOT A LUCKY NUMBERS
INPUT YOUR GUESS LUCKY NUMBER: -9
TRY AGAIN! -9 IS NOT A LUCKY NUMBERS
INPUT YOUR GUESS LUCKY NUMBER: 9
TRY AGAIN! 9 IS NOT A LUCKY NUMBERS
INPUT YOUR GUESS LUCKY NUMBER: 3
TRY AGAIN! 3 IS NOT A LUCKY NUMBERS
INPUT YOUR GUESS LUCKY NUMBER: 6
TRY AGAIN! 6 IS NOT A LUCKY NUMBERS
INPUT YOUR GUESS LUCKY NUMBER: 4
TRY AGAIN! 4 IS NOT A LUCKY NUMBERS
INPUT YOUR GUESS LUCKY NUMBER: 5
TRY AGAIN! 5 IS NOT A LUCKY NUMBERS
INPUT YOUR GUESS LUCKY NUMBER: 10
CONGRATS! 10 IS ONE OF THE LUCKY NUMBERS!
INPUT YOUR GUESS LUCKY NUMBER: 14
CONGRATS! 14 IS ONE OF THE LUCKY NUMBERS!
INPUT YOUR GUESS LUCKY NUMBER: 21
CONGRATS! 21 IS ONE OF THE LUCKY NUMBERS!
INPUT YOUR GUESS LUCKY NUMBER: aa
INVALID INPUT PLEASE TRY AGAIN!
INPUT YOUR GUESS LUCKY NUMBER: MARC
INVALID INPUT PLEASE TRY AGAIN!
INPUT YOUR GUESS LUCKY NUMBER: $$$$$$$$$$
INVALID INPUT PLEASE TRY AGAIN!
INPUT YOUR GUESS LUCKY NUMBER: 
= RESTART: C:/Users/Roden Marc/OneDrive/Desktop/DSA 2ND SEM PROJECTS SHIKII/GuessTheLuckyNumberChecker.py =
INPUT YOUR GUESS LUCKY NUMBER: 5
TRY AGAIN! 5 IS NOT A LUCKY NUMBERS
INPUT YOUR GUESS LUCKY NUMBER: 3
TRY AGAIN! 3 IS NOT A LUCKY NUMBERS
INPUT YOUR GUESS LUCKY NUMBER: 3
TRY AGAIN! 3 IS NOT A LUCKY NUMBERS
INPUT YOUR GUESS LUCKY NUMBER: $$$$$$
INVALID INPUT PLEASE TRY AGAIN!
INPUT YOUR GUESS LUCKY NUMBER: *****
INVALID INPUT PLEASE TRY AGAIN!
INPUT YOUR GUESS LUCKY NUMBER: FAMERO
INVALID INPUT PLEASE TRY AGAIN!
INPUT YOUR GUESS LUCKY NUMBER: 
======= RESTART: C:/Users/Roden Marc/OneDrive/Desktop/DSA 2ND SEM PROJECTS SHIKII/LeapYearChecker.py ======
INPUT YEAR TO KNOW: 5
INVALID INPUT ! PLEASE TRY AGAIN!
INPUT YEAR TO KNOW: 2024
NICE! 2024.0 IS A LEAP YEAR!!
INPUT YEAR TO KNOW: 
======= RESTART: C:/Users/Roden Marc/OneDrive/Desktop/DSA 2ND SEM PROJECTS SHIKII/LeapYearChecker.py ======
INPUT YEAR TO KNOW: 5
INVALID INPUT ! PLEASE TRY AGAIN!
INPUT YEAR TO KNOW: 
======= RESTART: C:/Users/Roden Marc/OneDrive/Desktop/DSA 2ND SEM PROJECTS SHIKII/LeapYearChecker.py ======
INPUT YEAR TO KNOW: 5
Traceback (most recent call last):
  File "C:/Users/Roden Marc/OneDrive/Desktop/DSA 2ND SEM PROJECTS SHIKII/LeapYearChecker.py", line 16, in <module>
    print ("NO!" , tempYEar, "IS NOT A LEAP YEAR")
NameError: name 'tempYEar' is not defined. Did you mean: 'tempYear'?

======= RESTART: C:/Users/Roden Marc/OneDrive/Desktop/DSA 2ND SEM PROJECTS SHIKII/LeapYearChecker.py ======
INPUT YEAR TO KNOW: 5
NO! 5 IS NOT A LEAP YEAR
INPUT YEAR TO KNOW: 3
NO! 3 IS NOT A LEAP YEAR
INPUT YEAR TO KNOW: 4
NICE! 4 IS A LEAP YEAR!!
INPUT YEAR TO KNOW: 0
INVALID INPUT ! PLEASE TRY AGAIN!
INPUT YEAR TO KNOW: -5
INVALID INPUT ! PLEASE TRY AGAIN!
INPUT YEAR TO KNOW: a
INVALID INPUT! IT MUST BE A POSITIVE INTEGER
INPUT YEAR TO KNOW: 5
NO! 5 IS NOT A LEAP YEAR
INPUT YEAR TO KNOW: 3
NO! 3 IS NOT A LEAP YEAR
INPUT YEAR TO KNOW: 2024
NICE! 2024 IS A LEAP YEAR!!
INPUT YEAR TO KNOW: 2028
NICE! 2028 IS A LEAP YEAR!!
INPUT YEAR TO KNOW: 2032
NICE! 2032 IS A LEAP YEAR!!
INPUT YEAR TO KNOW: 2020
NICE! 2020 IS A LEAP YEAR!!
INPUT YEAR TO KNOW: 2016
NICE! 2016 IS A LEAP YEAR!!
INPUT YEAR TO KNOW: 2020
NICE! 2020 IS A LEAP YEAR!!
INPUT YEAR TO KNOW: 2120
NICE! 2120 IS A LEAP YEAR!!
INPUT YEAR TO KNOW: 222
NO! 222 IS NOT A LEAP YEAR
INPUT YEAR TO KNOW: 0
INVALID INPUT ! PLEASE TRY AGAIN!
INPUT YEAR TO KNOW: 0
INVALID INPUT ! PLEASE TRY AGAIN!
INPUT YEAR TO KNOW: 0
INVALID INPUT ! PLEASE TRY AGAIN!
INPUT YEAR TO KNOW: a
INVALID INPUT! IT MUST BE A POSITIVE INTEGER
INPUT YEAR TO KNOW: a
INVALID INPUT! IT MUST BE A POSITIVE INTEGER
INPUT YEAR TO KNOW: a
INVALID INPUT! IT MUST BE A POSITIVE INTEGER
